version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
        interval: "weekly"
    target-branch: "master"
    reviewers:
      - "deNBI/portal-dev"
    open-pull-requests-limit: 15


