version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
        interval: "weekly"
    target-branch: "master"
    reviewers:
      - "deNBI/portal-dev"
    commit-message:
      prefix: "feat"
      include_scope: true
    open-pull-requests-limit: 15


