---
version: "3.4"
services:
  # global prometheus instance scraping data from the local instances
  global_prometheus:
    image: prom/prometheus
    networks:
      - portal
    expose:
      - "9090"
  influx_db:
    image: influxdb:1.7-alpine
    networks:
      - portal
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
      # automatically initialize the following db
      - INFLUXDB_DB=global_prometheus
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    expose:
      - "8086"
  grafana:
    image: grafana/grafana:5.4.0
    depends_on:
      - global_prometheus
    networks:
      - portal
    volumes:
      # currenntly no difference between dev and prod environment
      - ./prod/grafana/provisioning/:/etc/grafana/provisioning

# volumes:
#   local_prometheus:
#   global_prometheus:

networks:
  portal:
