---
version: "3.5"
services:
  # global prometheus instance scraping data from the local instances
  portal_prometheus:
    image: "prom/prometheus:${PROMETHEUS_TAG}"
    container_name: portal_prometheus
    networks:
      portal:
        aliases:
          - prometheus
    expose:
      - "9090"

  portal_influxdb:
    image: "influxdb:${INFLUXDB_TAG}"
    # a fixed name is necessary for the credits service to connect
    container_name: portal_influxdb
    networks:
      - portal
    environment:
      - INFLUXDB_GRAPHITE_ENABLED
      - INFLUXDB_REPORTING_DISABLED
      - INFLUXDB_DB
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_USER
      - INFLUXDB_USER_PASSWORD
    volumes:
      - "$INFLUXDB_VOLUME_PATH:/var/lib/influxdb"
      - "./prod/credits_influx_subscription.sh:/docker-entrypoint-initdb.d/01-sub.sh:ro"
    expose:
      - "8086"
    healthcheck:
      test: wget http://localhost:8086/ping -qO /dev/null || return 1
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always

  portal_grafana:
    image: "grafana/grafana:${GRAFANA_TAG}"
    container_name: portal_grafana
    depends_on:
      - portal_prometheus
    networks:
      - portal
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_SERVER_ROOT_URL
    volumes:
      - "./shared/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro"
      - "./shared/grafana/project_usages.json:/etc/grafana/provisioning/dashboards/project_usages.json:ro"

  portal_credits:
    image: "tluettje/os_credits:${CREDITS_TAG}"
    container_name: portal_credits
    restart: always
    networks:
      - portal
    healthcheck:
      test: wget http://localhost/ping -qO /dev/null || return 1
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - INFLUXDB_DB
      - INFLUXDB_USER
      - INFLUXDB_USER_PASSWORD
      - INFLUXDB_HOST
      - OS_CREDITS_PERUN_LOGIN
      - OS_CREDITS_PERUN_PASSWORD
      - OS_CREDITS_PERUN_VO_ID
    depends_on:
      - portal_influxdb

networks:
  portal:
