version: "3"
services:
  usage_exporter:
    environment:
      - USAGE_EXPORTER_START_DATE=2018-11-23T00:00:00Z
    image: tluettje/openstack-tenant-usage-exporter:v2
    env_file:
      - admin-openrc
    networks:
      - internal
    expose:
      - "8080"
  # local prometheus instance responsible for monitoring
  local_prometheus:
    build: ./local_prometheus
    networks:
      - internal
    ports:
      - "8080:9090"
    expose:
      - "9090"
    volumes:
      - "local_prometheus:/prometheus"
  # global prometheus instance scraping data from the local instance
  global_prometheus:
    build: ./global_prometheus
    networks:
      - internal
    ports:
      - "80:9090"
    volumes:
      - "global_prometheus:/prometheus"
  influx_db:
    image: influxdb:1.7-alpine
    networks:
      - internal
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
        # automatically initialize the following db
      - INFLUXDB_DB=global_prometheus
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=secret
      - INFLUXDB_USER=prometheus
      - INFLUXDB_USER_PASSWORD=secret
    expose:
      - "8086"

volumes:
  local_prometheus:
  global_prometheus:

networks:
  internal:
