# contains configuation for a production setup a at site with access to an
# openstack instance
---
version: "3.5"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "5"

services:
  site_exporter:
    image: "denbicloud/os_project_usage_exporter:2.4.0"
    container_name: project_usage_exporter
    networks:
      - usage_exporter
    logging:
      *default-logging
    environment:
      - USAGE_EXPORTER_START_DATE
      - USAGE_EXPORTER_UPDATE_INTERVAL
      - USAGE_EXPORTER_PROJECT_DOMAINS
      - USAGE_EXPORTER_PROJECT_ID
      - USAGE_EXPORTER_SIMPLE_VM_PROJECT_ID
      - USAGE_EXORTER_SIMPLE_VM_PROJECT_TAG
      - USAGE_EXPORTER_WEIGHTS_UPDATE_ENDPOINT
      - USAGE_EXPORTER_WEIGHT_UPDATE_FREQUENCY
      - USAGE_EXPORTER_START_DATE_ENDPOINT
      - USAGE_EXPORTER_VERBOSE_MODE
    expose:
      - "8080"
    ports:
      - "${EXPORTER_PORT}:8080"
  # prometheus instance responsible for monitoring
  site_prometheus:
    image: "prom/prometheus:v2.34.0"
    # use self build Dockerfile as alternative
    # build: prod/site_prometheus
    container_name: project_usage_prometheus
    logging:
      *default-logging
    networks:
      usage_exporter:
        aliases:
          - prometheus
    expose:
      - "9090"
  site_prometheus_proxy:
    # use the one below to have haproxy debug log directly to stdout including
    # every request with auth headers
    # image: mminks/haproxy-docker-logging:latest
    image: "haproxy:2.5.4-alpine"
    # use self build Dockerfile as alternative
    # build: prod/haproxy
    container_name: project_usage_proxy
    logging:
      *default-logging
    networks:
      - usage_exporter
    expose:
      # this port must be reachable by the portal prometheus instance
      # also setup some encryption to or in front of it, otherwise the whole
      # authentication stuff is useless
      - "80"
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - "./prod/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    environment:
      - PORTAL_AUTH_TOKEN
  site_grafana:
    image: "grafana/grafana:8.4.3"
    # use self build Dockerfile as alternative
    # build: prod/grafana
    container_name: project_usage_grafana
    logging:
      *default-logging
    depends_on:
      - site_prometheus
    networks:
      - usage_exporter
    volumes:
      - "./shared/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro"
      - "./shared/grafana/project_usages.json:/etc/grafana/provisioning/dashboards/project_usages.json:ro"
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
    expose:
      - "3000"
networks:
  usage_exporter:
