---
version: "3"
services:
  # sites producing dummy data for development environment without access to a
  # real openstack instance
  # {{{ site-a
  site-a_exporter:
    env_file:
      - dev/local_exporter.env
    environment:
      - USAGE_EXPORTER_DUMMY_FILE=/code/resources/low_usage.toml
    image: tluettje/os_project_usage_exporter:v2
    networks:
      - site-a
    expose:
      - "8080"
  site-a_prom_proxy:
    image: mminks/haproxy-docker-logging
    networks:
      - site-a
      - public
    expose:
      - "80"
    volumes:
      - "./dev/haproxy/etc:/usr/local/etc/haproxy:ro"
  # local prometheus instance responsible for monitoring
  site-a_prometheus:
    image: prom/prometheus
    volumes:
      - "./dev/local_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - site-a
    ports:
      - "8080:9090"
    expose:
      - "9090"
  # }}}
  # {{{ site-b
  site-b_exporter:
    env_file:
      - dev/local_exporter.env
    environment:
      - USAGE_EXPORTER_DUMMY_FILE=/code/resources/dummy_machines.toml
    image: tluettje/os_project_usage_exporter:v2
    networks:
      - site-b
    expose:
      - "8080"
  site-b_prom_proxy:
    image: mminks/haproxy-docker-logging
    networks:
      - site-b
      - public
    expose:
      - "80"
    volumes:
      - "./dev/haproxy/etc:/usr/local/etc/haproxy:ro"
  # local prometheus instance responsible for monitoring
  site-b_prometheus:
    image: prom/prometheus
    volumes:
      - "./dev/local_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - site-b
    ports:
      - "8081:9090"
    expose:
      - "9090"
  # }}}
  global_prometheus:
    volumes:
      - "./dev/global_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - public
      - site-a
      - site-b
  influx_db:
    env_file:
      - ./dev/influx_db.env
  grafana:
    env_file:
      - ./dev/grafana.env
networks:
  site-a:
  site-b:
  public:
