[[weights]]
resource_set_timestamp = 1594771200 # 2020-07-15T00:00:00+00:00 in ISO 8601
vcpus = [
    {value = 2, weight = 1},
    {value = 4, weight = 2},
]
memory_mb = [
    {value = 8192, weight = 2},
]

[[weights]]
resource_set_timestamp = 1594339200 # 2020-07-10T00:00:00+00:00 in ISO 8601
vcpus = [
    {value = 2, weight = 2},
    {value = 4, weight = 3},
]
memory_mb = [
    {value = 8192, weight = 3},
]
