---
global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s  # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).


scrape_configs:
  - job_name: 'self_monitoring'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'denbi_cloud_project_usage'
    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        # do not collect any metrics besides the one we are interested in
        - '{job="project_usages",__name__=~"project_.*_usage"}'

    static_configs:
      - targets: ['thinki.local:8080']
        labels:
          location: Bielefeld-Dev
          location_id: 8484

    bearer_token: "DontUseThisInProduction"

remote_write:
  # yamllint disable-line rule:line-length
  - url: "http://portal_prometheus_influxdb:8086/api/v1/prom/write?db=portal_prometheus&u=prometheus&p=secret"

remote_read:
  # yamllint disable-line rule:line-length
  - url: "http://portal_prometheus_influxdb:8086/api/v1/prom/read?db=portal_prometheus&u=prometheus&p=secret"
