---
version: "3.4"
services:
  prometheus:
    volumes:
      - "./prod/global_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
  influx_db:
    env_file:
      - ./prod/influx_db.env
    volumes:
      - portal_influxdb:/var/lib/influxdb
  grafana:
    env_file:
      - ./prod/portal_grafana.env
volumes:
  portal_influxdb:
