---
version: "3"
services:
  global_prometheus:
    volumes:
      - "./prod/global_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  influx_db:
    env_file:
      - ./prod/influx_db.env
  grafana:
    env_file:
      - ./prod/grafana.env
