# contains configuation for a production setup a at site with access to an
# openstack instance
---
version: "3"
services:
  exporter:
    image: tluettje/os_project_usage_exporter:v2
    env_file:
      - usage-openrc
    networks:
      - usage_exporter
    expose:
      - "8080"
  # prometheus instance responsible for monitoring
  prometheus:
    image: prom/prometheus
    networks:
      - usage_exporter
    ports:
      - "8080:9090"
    expose:
      - "9090"
    volumes:
      - "./prod/local_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  prometheus_proxy:
    image: mminks/haproxy-docker-logging
    networks:
      - usage_exporter
    expose:
      # this port must be reachable by the global prometheus instance inside the
      # portal
      # also setup some encryption to or in front of it, otherwise the whole
      # authentication stuff is useless
      - "80"
    volumes:
      - "./prod/haproxy/etc/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
networks:
  usage_exporter
