---
version: "3.4"
services:
  prometheus:
    # in case of a reverse proxy insert the full path to prometheus here
    # command:
      # - --web.external-url=https://portal-dev.denbi.de/prom
    volumes:
      - "./prod/global_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
  influx_db:
    env_file:
      - ./prod/influx_db.env
    volumes:
      - portal_influxdb:/var/lib/influxdb
  grafana:
    env_file:
      - ./prod/grafana.env
volumes:
  portal_influxdb:
